###### Импортируем библиотеки

In [1]:
import pandas as pd

###### Загружаем набор данных с помощью pandas

In [2]:
anime_df = pd.read_csv('data/anime.csv')
anime_df

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

###### Вывод технической информации о датасете

Описание типов переменных: anime_id - порядковая переменная, name - строковая переменная, genre - категориальная переменная, type - категориальная переменная, episodes - числовая переменная, rating - непрерывная переменная, members - числовая переменная.

In [3]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

###### Вывод статистических характеристик набора

Статистические характеристики числовых полей: min - минимум, max - максимум, mean - среднее, 50% - медиана

In [4]:
anime_df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

###### Проверка на пустые значения полей

In [5]:
row_with_na = anime_df.isna().any(axis=1)
anime_df[row_with_na]

,anime_id,name,genre,type,episodes,rating,members
2844,33242,IS: Infinite Stratos 2 - Infinite Wedding,NaN,Special,1,7.15,6604
3541,33589,ViVid Strike!,NaN,TV,12,6.96,12345
6040,29765,Metropolis (2009),NaN,Movie,1,6.27,313
6646,32695,Match Shoujo,NaN,ONA,1,6.02,242
7018,33187,Katsudou Shashin,NaN,Movie,1,5.79,607
...,...,...,...,...,...,...,...
12274,34492,Nuki Doki! Tenshi to Akuma no Sakusei Battle -...,Hentai,OVA,Unknown,NaN,392
12279,34491,Sagurare Otome The Animation,Hentai,OVA,1,NaN,79
12280,34312,Saimin Class,Hentai,OVA,Unknown,NaN,240
12282,34388,Shikkoku no Shaga The Animation,Hentai,OVA,Unknown,NaN,195
12285,34399,Taimanin Asagi 3,"Demons, Hentai, Supernatural",OVA,Unknown,NaN,485

###### Срезы по именам полей

In [6]:
anime_df.loc[:, 'anime_id']

0        32281
1         5114
2        28977
3         9253
4         9969
         ...
12289     9316
12290     5543
12291     5621
12292     6133
12293    26081
Name: anime_id, Length: 12294, dtype: int64

In [7]:
anime_df.loc[:, 'name':'type']

,name,genre,type
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV
3,Steins;Gate,"Sci-Fi, Thriller",TV
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV
...,...,...,...
12289,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA
12290,Under World,Hentai,OVA
12291,Violence Gekiga David no Hoshi,Hentai,OVA
12292,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA
12293,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie

In [8]:
anime_df.loc[:, 'genre':'genre']

                                                   genre
0                   Drama, Romance, School, Supernatural
1      Action, Adventure, Drama, Fantasy, Magic, Mili...
2      Action, Comedy, Historical, Parody, Samurai, S...
3                                       Sci-Fi, Thriller
4      Action, Comedy, Historical, Parody, Samurai, S...
...                                                  ...
12289                                             Hentai
12290                                             Hentai
12291                                             Hentai
12292                                             Hentai
12293                                             Hentai

[12294 rows x 1 columns]

In [9]:
anime_df.loc[5:12, 'name':'episodes']

,name,genre,type,episodes
5,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10
6,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148
7,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110
8,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1
9,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13
10,Clannad: After Story,"Drama, Fantasy, Romance, Slice of Life, Supern...",TV,24
11,Koe no Katachi,"Drama, School, Shounen",Movie,1
12,Gintama,"Action, Comedy, Historical, Parody, Samurai, S...",TV,201

###### Срез по индексам

In [10]:
anime_df.iloc[:, [1, 3]]

                                                    name   type
0                                         Kimi no Na wa.  Movie
1                       Fullmetal Alchemist: Brotherhood     TV
2                                               Gintama°     TV
3                                            Steins;Gate     TV
4                                          Gintama&#039;     TV
...                                                  ...    ...
12289       Toushindai My Lover: Minami tai Mecha-Minami    OVA
12290                                        Under World    OVA
12291                     Violence Gekiga David no Hoshi    OVA
12292  Violence Gekiga Shin David no Hoshi: Inma Dens...    OVA
12293                   Yasuji no Pornorama: Yacchimae!!  Movie

[12294 rows x 2 columns]

###### Фильтрации по значениям полей

In [11]:
rating_df = anime_df[(anime_df.rating == 8.6) | (anime_df.rating == 9)]
rating_df

,anime_id,name,genre,type,episodes,rating,members
63,21899,Gintama: Yorinuki Gintama-san on Theater 2D,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,2,8.6,11104
64,26055,JoJo no Kimyou na Bouken: Stardust Crusaders 2...,"Action, Adventure, Drama, Shounen, Supernatural",TV,24,8.6,93657
8234,33950,Black Clover,"Action, Comedy, Fantasy, Magic, Shounen",Special,1,8.6,2247
9539,26259,Mienu Me ni Kanjita Kumotoriyama no Asahi,"Drama, Kids",OVA,1,9.0,47
9577,33980,Mirai ni Mukete: Bousai wo Kangaeru,Drama,Movie,1,9.0,77
9831,26145,Okaachan Gomen ne,"Historical, Kids",Movie,1,9.0,47
10136,34191,Santa-san wa Dai Isogashi,"Fantasy, Kids",OVA,1,9.0,25
10181,32627,Shaka no Shougai,Historical,Movie,1,9.0,31
10191,32796,Shenmi Shijie Lixian Ji,"Adventure, Comedy, Fantasy",Movie,1,9.0,37

In [12]:
anime_df[(anime_df['members'] >= 313) & (anime_df['members'] <= 404)]

,anime_id,name,genre,type,episodes,rating,members
1600,11835,Qin Shiming Yue Zhi: Zhu Zi Bai Jia,"Action, Fantasy, Historical, Martial Arts",TV,34,7.49,369
2531,11841,Qin Shiming Yue Zhi: Ye Jin Tianming,"Action, Fantasy, Historical, Martial Arts",TV,18,7.24,366
2905,6202,Daisetsusan no Yuusha Kibaou,"Adventure, Drama",Special,1,7.13,322
2976,9348,Chibi Maruko-chan: Watashi no Suki na Uta,"Comedy, Slice of Life",Movie,1,7.11,401
3039,5895,Tistou Midori no Oyayubi,"Historical, Magic",Movie,1,7.10,332
...,...,...,...,...,...,...,...
12228,5547,Kateikyoushi Bishounen Kari,Hentai,OVA,1,5.03,315
12235,5561,Yayoi,Hentai,OVA,1,4.94,340
12244,11141,Blue Seagull,"Action, Hentai",Movie,1,4.60,337
12257,34168,Hataraku Otona no Renai Jijou The Animation,Hentai,OVA,1,NaN,331
12274,34492,Nuki Doki! Tenshi to Akuma no Sakusei Battle -...,Hentai,OVA,Unknown,NaN,392

In [13]:
anime_df.loc[lambda anime_df: (anime_df['members'] < 30) & (anime_df['type'] == 'OVA'), 'genre']

8152     Drama, Historical
8339     Drama, Historical
8367                Comedy
8598            Historical
8638     Drama, Historical
9701            Historical
10136        Fantasy, Kids
10146    Drama, Historical
10500    Drama, Historical
Name: genre, dtype: object

###### Сортировка отфильтрованного по рейтингу набора данных по возрастанию значений поля members

In [14]:
rating_df.sort_values(by='members', ascending=True)

,anime_id,name,genre,type,episodes,rating,members
10136,34191,Santa-san wa Dai Isogashi,"Fantasy, Kids",OVA,1,9.0,25
10181,32627,Shaka no Shougai,Historical,Movie,1,9.0,31
10191,32796,Shenmi Shijie Lixian Ji,"Adventure, Comedy, Fantasy",Movie,1,9.0,37
9539,26259,Mienu Me ni Kanjita Kumotoriyama no Asahi,"Drama, Kids",OVA,1,9.0,47
9831,26145,Okaachan Gomen ne,"Historical, Kids",Movie,1,9.0,47
9577,33980,Mirai ni Mukete: Bousai wo Kangaeru,Drama,Movie,1,9.0,77
8234,33950,Black Clover,"Action, Comedy, Fantasy, Magic, Shounen",Special,1,8.6,2247
63,21899,Gintama: Yorinuki Gintama-san on Theater 2D,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,2,8.6,11104
64,26055,JoJo no Kimyou na Bouken: Stardust Crusaders 2...,"Action, Adventure, Drama, Shounen, Supernatural",TV,24,8.6,93657

###### Группировка данных по среднему значению рейтинга для поля type

In [15]:
anime_df.groupby(['type'])[['rating']].mean()

           rating
type
Movie    6.318058
Music    5.588996
ONA      5.643298
OVA      6.375221
Special  6.523501
TV       6.902299

###### Загрузка ещё одного набора данных

In [16]:
rating_df = pd.read_csv('data/rating.csv')
rating_df.columns

Index(['user_id', 'anime_id', 'rating'], dtype='object')

###### Объединение таблиц с типом присоединения inner

In [17]:
anime_df.merge(rating_df, how = 'inner', left_on = 'anime_id', right_on = 'anime_id')

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99,5
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152,10
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244,10
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271,10
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278,-1
...,...,...,...,...,...,...,...,...,...
7813722,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,39532,-1
7813723,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,48766,-1
7813724,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365,4
7813725,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,27364,-1
7813726,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,48766,-1

###### Объединение таблиц с типом присоединения left

In [18]:
anime_df.merge(rating_df, how = 'left', left_on = 'anime_id', right_on = 'anime_id')

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,99.0,5.0
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,152.0,10.0
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,244.0,10.0
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,271.0,10.0
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630,278.0,-1.0
...,...,...,...,...,...,...,...,...,...
7814819,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,39532.0,-1.0
7814820,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,48766.0,-1.0
7814821,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175,60365.0,4.0
7814822,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,27364.0,-1.0
7814823,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142,48766.0,-1.0

###### Объединение таблиц с типом присоединения right

In [19]:
anime_df.merge(rating_df, how = 'right', left_on = 'anime_id', right_on = 'anime_id')

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,20,Naruto,"Action, Comedy, Martial Arts, Shounen, Super P...",TV,220,7.81,683297.0,1,-1
1,24,School Rumble,"Comedy, Romance, School, Shounen",TV,26,8.06,178553.0,1,-1
2,79,Shuffle!,"Comedy, Drama, Ecchi, Fantasy, Harem, Magic, R...",TV,24,7.31,158772.0,1,-1
3,226,Elfen Lied,"Action, Drama, Horror, Psychological, Romance,...",TV,13,7.85,623511.0,1,-1
4,241,Girls Bravo: First Season,"Comedy, Ecchi, Fantasy, Harem, Romance, School",TV,11,6.69,84395.0,1,-1
...,...,...,...,...,...,...,...,...,...
7813732,16512,Devil Survivor 2 The Animation,"Action, Demons, Supernatural",TV,13,7.06,101266.0,73515,7
7813733,17187,Ghost in the Shell: Arise - Border:1 Ghost Pain,"Mecha, Police, Psychological, Sci-Fi",Movie,1,7.64,31747.0,73515,9
7813734,22145,Kuroshitsuji: Book of Circus,"Comedy, Demons, Fantasy, Historical, Shounen, ...",TV,10,8.37,122895.0,73515,10
7813735,790,Ergo Proxy,"Mystery, Psychological, Sci-Fi",TV,23,8.03,265005.0,73516,9
7813736,8074,Highschool of the Dead,"Action, Ecchi, Horror, Supernatural",TV,12,7.46,535892.0,73516,9

###### Объединение таблиц с типом присоединения outer

In [20]:
anime_df.merge(rating_df, how = 'outer', left_on = 'anime_id', right_on = 'anime_id')

,anime_id,name,genre,type,episodes,rating_x,members,user_id,rating_y
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0,99.0,5.0
1,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0,152.0,10.0
2,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0,244.0,10.0
3,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0,271.0,10.0
4,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630.0,278.0,-1.0
...,...,...,...,...,...,...,...,...,...
7814829,30913,NaN,NaN,NaN,NaN,NaN,NaN,51693.0,-1.0
7814830,30913,NaN,NaN,NaN,NaN,NaN,NaN,62549.0,-1.0
7814831,30924,NaN,NaN,NaN,NaN,NaN,NaN,19104.0,-1.0
7814832,30924,NaN,NaN,NaN,NaN,NaN,NaN,62549.0,-1.0
7814833,20261,NaN,NaN,NaN,NaN,NaN,NaN,48766.0,-1.0